### ISSUE TITLE
Cancelling agreement with status PENDING is currently not possible

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-recurring-api#111]
Hi,

We create agreements using `POST /v2/agreements` which inits a checkout process on the customers phone.

If the customer want to cancel this process, there is currently no possible way to cancel this using the Rest API, as `PATCH /v2/agreements/{agreementId}` does not accept a status change to 'STOPPED' unless the current status of the agreement is 'ACTIVE'.

Can you also allow the status to be changed to 'STOPPED' for 'PENDING' agreements?
Else we can't cancel the agreements before it expires & and user might fulfill a cancelled order.

Ref: https://vippsas.github.io/vipps-recurring-api/shins/index.html?http#update-an-agreement

**Comment by cloveras** [comment]
Hi @steffanhalv 

Just a short comment from one of the developers:

_Pending agreements is automatically moved to expired if user does nothing. If the user wants to stop it, they can cancel it from the app._

Christian, Vipps

**Comment by steffanhalv** [comment]
@cloveras Thank you for fast answer.

It will still not solve this issue though.
Take the following use case:

1. The customer creates a plan on our site using web browser & confirms using vipps app
2. The customer wants to upgrade the plan and tries to do this using our website & the vipps app
3. The customer comes all the way so he/she only have to press the confirm button in the app
4. Now the customer sees that it was the wrong upgrade plan and clicks '**cancel**' in the browser (**or the back arrow in browser**)
5. The user initiates a new upgrade selecting the correct plan, but the vipps app has not changed its state & user clicks 'confirm' which now will be the wrong payment.

This could be avoided by allowing to cancel a pending agreement from the Rest API @cloveras

**Comment by cloveras** [comment]
Hi @steffanhalv 

Sorry for the extremewly slow response here. I have asked the team to provide an update.

Christian, Vipps.

**Comment by cloveras** [comment]
Can you provide some info here, @rognlien?

**Comment by skasti** [comment]
The correct way to handle this is for you to not allow step 5 "The user initiates a new upgrade selecting the correct upgrade", as the user still has a pending agreement, and ask them to cancel the process in the app.

In general; you should never allow a user to draft a new agreement if they already have a pending agreement. In such cases they need to be asked to cancel the flow in the app before continuing to maintain a good user experience.
