### ISSUE TITLE
Update an Agreement - possible to change period/interval in update request

### ISSUE THREAD

**Issue by kmieciu85** [vippsas/vipps-recurring-api#115]
Today it is possible to update the price in agreement.

Do you have any plans to have an option to update period/interval in update request?

It is possible that customer may change an active subscription to different period, will be fine to have possibility to change the subscription to new one period/intervals (in addition to price).

**Comment by cloveras** [comment]
Hi @kmieciu85 

Sorry for the extremewly slow response here. I have asked the team to provide an update.

Christian, Vipps.

**Comment by kmieciu85** [comment]
Hi @cloveras 

Did you get response from the team? Do you have any plans to have an option to update period/interval in update request?

Karol

**Comment by cloveras** [comment]
Not yet, sorry. We can follow up on Slack.

Christian, Vipps

**Comment by kmieciu85** [comment]
👍

**Comment by Jarneid** [comment]
As answered on Slack:

Vi kommer til å gjøre en større jobb på produktsiden hvor vi skal se på hvor mye "fleksibilitet" vi skal tillate i produktet. Pt kommer vi ikke til å gjøre noen endringer, men vi kommer absolutt til å ta med deres innspill inn i vurderingene.

**Comment by cloveras** [comment]
From "Intervals" the API guide: https://github.com/vippsas/vipps-recurring-api/blob/master/vipps-recurring-api.md#intervals

"Please note: It is not possible to change intervals. If the user has accepted a yearly interval, the agreement can not be changed to a monthly agreement. This requires a new agreement and a new consent from the user. It is possible to make a monthly agreement and only charge some of the months. The general rule: Be as customer friendly and easy to understand as possible."


Closing this.
