### ISSUE TITLE
Wrong orderId-pattern when creating a charge

### ISSUE THREAD

**Issue by OlaAlsaker** [vippsas/vipps-recurring-api#126]
[Documentation says](https://vippsas.github.io/vipps-recurring-api/#/Charge%20Controller/createCharge) that the `orderId` field in a `ChargeRequest` has the following pattern:
```
pattern: ^[a-zA-Z0-9-]{1,40}$
```

But, when I try to send in `acme-shop-123-order123abc` as `orderId` I get an error:
```
"field":"orderId",
"message":"must match \"[a-zA-Z0-9]+\"",
"code":"orderid.pattern",
```

It seems like the `-` _(hyphen)_ is missing from the pattern. If I change the `orderId` to `acmeshop123order123abc`, the request succeeds. This is in the **test-environment**, I haven't tested it in production yet.

**Comment by cloveras** [comment]
Hi @OlaAlsaker 

thanks for reporting this! I’m not sure where the error is, but we will update here when we know. 

Christian, Vipps

**Comment by cloveras** [comment]
Hi @OlaAlsaker 

This was fixed in https://github.com/vippsas/vipps-recurring-api/commit/539801f62035fe351b5b8269ed477ca07c7d6c93

Thanks for helping, and sorry for the error.

Christian, Vipps
