### ISSUE TITLE
Listing charges for a nonexistent agreement returns 400, expected 404

### ISSUE THREAD

**Issue by torfjor** [vippsas/vipps-recurring-api#134]
Hi!

I'd expect a 404, in line with the other endpoints in the charge controller. This would let us skip poking in the response for code `recurring.merchant-api.invalid.agreementId`.

**Comment by torfjor** [comment]
Looks like this went live without mention in the docs?

**Comment by cloveras** [comment]
Hi @torfjor 

Whups..

I'll have the team check. Thanks for the follow-up, and sorry for the late response. 

Christian, Vipps
