### ISSUE TITLE
Wrong OAS return status code for Update Agreement 

### ISSUE THREAD

**Issue by esbenbach** [vippsas/vipps-recurring-api#135]
The OAS spec for the PATCH operation Update Agreement (https://vippsas.github.io/vipps-recurring-api/#/Agreement%20Controller/updateAgreement) has 201 as the "success" response status code, but at least in the test environment the success response that we actually get is 200.

Not a huge problem but our auto-generated client complains non the less.

**Comment by cloveras** [comment]
Hi @esbenbach

Sorry for the late response.

I'll have the team look info this, and hopefully fix it quickly. 

Christian, Vipps
