### ISSUE TITLE
Recurring payments: support for scheduled start of agreement?

### ISSUE THREAD

**Issue by jmyrland** [vippsas/vipps-recurring-api#144]
Is it possible to set a start date for an agreement?

For example, we have a product that costs 1000 kr (initial payment). With the purchase of this product, a subscription is included for free for a year. After one year, the subscription should be 50 kr per month.

I've seen that `Campaign` might be an option in this case, but it seems that it does not support `campaignPrice` set to `0` ([limited to atleast `100`](https://vippsas.github.io/vipps-recurring-api)).

Is there any other ways to achieve the example above?

**Comment by cloveras** [comment]
Hi @jmyrland 

Sorry for the late reply here too. 🙈

We do support 0 kr now.

Christian, Vipps

**Comment by frodsan** [comment]
`campaignPrice` can be set to `0` now. Re-open if the issue continues. Thanks 😄
