### ISSUE TITLE
POST:/agreements not working (incorrect path?)

### ISSUE THREAD

**Issue by jmyrland** [vippsas/vipps-recurring-api#146]
I think the docs are outdated, when referring to the path of how to create draft documents.

I cannot get `POST:/agreements` to work, as I get the following 404 response:
```
404: "APIM Resource Not Found"
```

I see that the postman templates uses the path `POST:/recurring/v2/agreements`. This path works as expected.

**Comment by cloveras** [comment]
Hi @jmyrland 

Sorry for the late reply.

The Postman collection can be used to find the correct requests, URLs, etc.

The Swagger UI representation shoyuld also be correct: https://vippsas.github.io/vipps-recurring-api/

Christian, Vipps
