### ISSUE TITLE
Improve the way to retrieve last charge of agreement

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-recurring-api#164]
Sometimes one must show the last charge in the context of the agreement. There are multiple scenarios where this may be needed, below some examples:
- show status of the last charge in the Admin interface
- use last charge to schedule upcoming one based on agreements interval value
- allow a quick way of interacting with the last charge - ex. cancel it before it's CHARGED

Currently to achieve that one must 
1. fetch agreement 
2. fetch a list of agreement charges
3. sort charges by the due date
4. filter out all charges but the last

This procedure can be expensive as it requires at least 2 API calls and some manual manipulation of the data set. And since the data set is growing linearly it is more expensive which every charge iteration. This gets even more expensive if one operates on a list of agreements rather than a single agreement.

The example admin view which is difficult to achieve:
| Agreement ID | Amount | Interval | Start date | Last charge date | Last charge status |
| - | - | - | - | - | - |
| agr_123 | 100,- | MONTHLY | 01-01-2021 | 01-12-2021 | FAILED |
| agr_234 | 200,- | MONTHLY | 03-03-2021 | 03-12-2021 | CHARGED |

## Proposed solution
Since we (the end-users of your API) have no means of joining extra data as part of a single request (which could be done if you were using ex. GraphQL) it would make it much easier for us to provide administration interfaces if you could join the following data into the list of agreements (GET /recurring/v2/agreements) as well as single agreement entry (GET /recurring/v2/agreements/{agreementId}):
- last charge created against the agreement (by date of creation)
- last finalized charge (CHARGED/FAILED/REFUNDED)

## Final notes
There are of course some pros and cons of this approach. The main con is - there will be more data to include when fetching agreements. Also, DB queries are gonna be more complex and slower on your end. The main pro is - there will be fewer queries hitting your API as more meaningful data will be included out-of-the-box in agreements/agreemeent endpoints

**Comment by cloveras** [comment]
See: https://github.com/vippsas/vipps-recurring-api/pull/166

**Comment by cloveras** [comment]
I'll leave it to @rognlien to answer this _properly_.

**Comment by zaporylie** [comment]
Not sure how #166 is relevant here but I'll wait for the _proper_ answer from @rognlien

**Comment by zaporylie** [comment]
Looks like v3 of recurring API is coming soon. Any chance this issue can be addressed before v3 is published? Or perhaps added in a backward-compatible way (it's just an addition). As I've mentioned in the issue summary we're struggling to provide merchants a contextual overview of agreements, together with last charge status, as it requires too many queries from us to your API.

cc @cloveras @rognlien

**Comment by rognlien** [comment]
Hello, sorry for the incredibly slow response.
I think these are good suggestions. However, we are not really keen on bundling together data that can change independently. (Such as Agreements and Charges). This could, as you say be solved more elegantly with GraphQL (or something similar).

But, would something like /recurring/v2/agreements/{agreementId}/charges/latest help?

**Comment by zaporylie** [comment]
Unfortunately, that wouldn't reduce the number of requests to your API because for the simple task of fetching a list of the last charges across all active agreements we'd still have to:
- fetch a list of all agreements
- iterate over agreements and fetch the last charge for each one of them

So the number of queries is N + 1 where N is the number of active agreements.

The addition you mention only reduces the complexity within the merchant's application but it doesn't mitigate the bottleneck which currently is the number of HTTP requests toward your API.

The proposal I've made would require only 1 request.

Alternatively, you could make it possible to query a list of charges in an agreement-agnostic way. Ie. `GET /recurring/v2/charges?from={datetime}` or `GET /recurring/v2/charges/latest` and include the agreement ID along with each charge obtained that way.

**Comment by rognlien** [comment]
Ok, I understand, but for the first example point 3 and 4 (sorting and filtering) should be negligible compared to. So we are left with the cost of the HTTP calls. How many agreements do you typically want to show at the same time?
When fetching several agreements/charges, could you perhaps consider parallelising them?
I will need to think a little more about this.

**Comment by zaporylie** [comment]
> Ok, I understand, but for the first example point 3 and 4 (sorting and filtering) should be negligible compared to fetching the data

Yes, that is what I meant by:

> The addition you mention only reduces the complexity within the merchant's application but it doesn't mitigate the bottleneck which currently is the number of HTTP requests toward your API.

When it comes to

> So we are left with the cost of the HTTP calls. How many agreements do you typically want to show at the same time?

It varies but quite often we need to query through all active agreements for reporting reasons. Which quite often means several thousands of active agreements. We have a platform where we support several merchants which brings the total number to several thousand. The limited queryability of the agreement/charge data is currently a huge bottleneck for us.

>  When fetching several agreements/charges, could you perhaps consider parallelising them?

That will only reduce the time needed for fetching data - it won't reduce the complexity of the operation and the load on your side that could be avoided if we only load data we care about.

**Comment by ameliemaucade** [comment]
Hi @zaporylie and sorry again for not answering way earlier. With our current set up, we cannot expose an endpoint to list charges in an agreement agnostic way. Queries for each request would be to costly in terms of performances. 
I understand why this type of endpoint is needed but unfortunately it has not been prioritised yet. We will look how we can make it easier for the scenarios you mentioned but we have no timeline on when we will start.

**Comment by ameliemaucade** [comment]
Hi @zaporylie and sorry again for not answering way earlier. With our current set up, we cannot expose an endpoint to list charges in an agreement agnostic way. Queries for each request would be to costly in terms of performances. 
I understand why this type of endpoint is needed but unfortunately it has not been prioritised yet. We will look how we can make it easier for the scenarios you mentioned but we have no timeline on when we will start.

**Comment by zaporylie** [comment]
Hi @ameliemaucade 

> Queries for each request would be to costly in terms of performances.

Just so you know, the performance issues are still valid if the responsibility is moved over to the merchant, and brings additional performance overhead due to extra networking.

> We will look how we can make it easier for the scenarios you mentioned

Given you understand the issue in question described almost 2 years ago and would in fact consider it why closing this issue as _not planned_?

**Comment by ameliemaucade** [comment]
Hello! 
We are aware that the responsibility is moved over to the merchants, I have noted your request and it is will something will consider in the future. However we do not currently have plans for implementing this, that is why I had closed the issue as not planned. But I realise now should have just closed it and not mark it as "not planned" since it's more "not planned just yet"
