### ISSUE TITLE
Swagger documentation is currently broken

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-recurring-api#168]
The documentation available under https://vippsas.github.io/vipps-recurring-api/ is currently broken:
![image](https://user-images.githubusercontent.com/1690685/148942380-e7c00458-d45a-4249-b316-68e155a98d82.png)

**Comment by zaporylie** [comment]
The reason seems to be incorrect indentation on the following line:
https://github.com/vippsas/vipps-recurring-api/blob/master/docs/openapi.yaml#L1214

**Comment by flinkgutt** [comment]
Thank you for your error report! :-)

Fixed this with commit https://github.com/vippsas/vipps-recurring-api/commit/675d48cb03c740d1493d125efe497ff62d981dda
