### ISSUE TITLE
Scheduled action issue

### ISSUE THREAD

**Issue by esbnews** [vippsas/vipps-recurring-api#280]
Hi

My system generates an error connected to Vipps fast trekk and Woocommerce Subscriptions when a recurring action runs:

"scheduled action 188853 (subscription payment) failed to finish processing due to the following error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /customers/3/d/8/xxxxx.no/httpd.www/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/templates/emails/customer-processing-renewal-order.php:19"

I wonder how to work this out, and am not sure if it's a Vipps problem or Woocommerce Subscriptions problem. I got the full errorlog if anyone can look at this.

Best regards, Esben Holm Eskelund

**Comment by cloveras** [comment]
(I have notified the plugin developers, but still..)

**Comment by esbnews** [comment]
Thanx for the help! I have probably stepped into a faulty formatting-issue in a translations file causing this error.
