### ISSUE TITLE
Time-out errors from cURL

### ISSUE THREAD

**Issue by magnuskl** [vippsas/vipps-recurring-api#366]
Starting this afternoon, Vipps Recurring Payments for WooCommerce reports hundreds of time-out errors from cURL:

```
2023-05-31T16:11:47+00:00 DEBUG 
==== Vipps Recurring Version: 1.15.0 ====
==== Start Log ====
HTTP Response Error (0): 500 cURL error 28: Connection timed out after 10001 milliseconds (recurring/v3/agreements/agr_bhJ22qz/charges/chr-naQULH6) with request body: []. The response was: 
==== End Log ====
```

These errors prevent some, but not all, charges from being made. Is there an intermittent problem with the API? Do you have any other ideas about what the cause may be?

**Comment by cloveras** [comment]
Hello! 

We have no other reports of problems (see https://developer.vippsmobilepay.com/docs/vipps-developers/developer-resources/status-pages/), so this _may_ be a problem at your end. 

Here is some general info on how what we need to help: https://developer.vippsmobilepay.com/docs/vipps-developers/contact/#what-to-include-in-the-email

The developer of the plugin can add some more details here..

**Comment by magnuskl** [comment]
I captured one of the failing API request and put it into a cURL script—keys, token, and all. Running the script on my own laptop fetches the correct data from the API every time; however, running the script from the web server _sometimes_ fails to establish a TCP connection to the API.

```
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 20.123.124.48...
* TCP_NODELAY set
* connect to 20.123.124.48 port 443 failed: Connection timed out
* Failed to connect to api.vipps.no port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to api.vipps.no port 443: Connection timed out
```

Can this error be due to rate limitation?

**Comment by magnuskl** [comment]
I suspect that the problem is due to networking issues on our side. I will investigate further and post an update.
