### ISSUE TITLE
Free Trial using Vipps

### ISSUE THREAD

**Issue by paulorodriguesedu** [vippsas/vipps-recurring-api#391]
Hello
I'm trying to understand how to reach the feature "free trial" for example for 14 days and after using payment using vipps.
Can someone tell me some ideas?

My first idea was using agreement with dueDate and use reserve_capture but when i use dueDate for next 14 days, the charge it's pointing for the current date.
It's error from your API or what?

Example after creating agreement:

```
{
    "id": "chr-ssss",
    "status": "RESERVED",
    "due": "2023-09-25T16:55:45Z",
    "amount": 1000,
    "amountRefunded": 0,
    "amountCaptured": 0,
    "transactionId": "99999999",
    "description": "Premium",
    "type": "INITIAL",
    "failureReason": null,
    "failureDescription": null
}
```

**Comment by paulorodriguesedu** [comment]
@rognlien

**Comment by paulorodriguesedu** [comment]
@ameliemaucade

**Comment by ameliemaucade** [comment]
Hi, are you referring to the campaigns in Vipps recurring? 
https://developer.vippsmobilepay.com/docs/APIs/recurring-api/vipps-recurring-api/#campaigns
If you can send me some examples of requests and charge ids, I can help finding out what is wrong here.

**Comment by ameliemaucade** [comment]
Initial charges are always processed when the agreement is accepted by the suer. Initial charges's due date can not be defined by the merchant. 
You can instead draft an agreement without initial charge and once the agreement is activated, create a charge with a due date set in 14 days.

**Comment by paulorodriguesedu** [comment]
I have created with due date with 14 days, but when i see the due date its pointing for the current date, may be an issue on your api?

**Comment by ameliemaucade** [comment]
If you can provide agreement ids and/or charge ids, I can help finding out what is the issue.

**Comment by paulorodriguesedu** [comment]
agr_sDg5TbA this is an example @ameliemaucade

**Comment by paulorodriguesedu** [comment]
chr-KA2Wtb5 it's reserved but due": "2023-09-28T14:41:49Z",
