### ISSUE TITLE
How does interval with DAY works?

### ISSUE THREAD

**Issue by sjelfull** [vippsas/vipps-recurring-api#77]
Do you have some documentation on how DAY intervals works?

Would we be able to say, charge someone on Monday, Wednesday and Sunday?

**Comment by tht13** [comment]
`DAY` interval works by presenting to the user in the Vipps app that the agreement will be charged by you the merchant every N days, where N is `intervalCount`. It does not specify the day of the week.

So `interval: DAY` and `intervalCount: 4` will be presented as "Charged every 4 days"

**Comment by cloveras** [comment]
Hi, @sjelfull 

I've added a new example, and will close this issue now.

https://github.com/vippsas/vipps-recurring-api/commit/e21f076597d853622acb6fb80a074392a6b5eba7

Christian, Vipps
