### ISSUE TITLE
POST create initial agreement call failing on date validation error for end date

### ISSUE THREAD

**Issue by CraigAndrew** [vippsas/vipps-recurring-api#85]
Validation failing on campaign end date:
[
    {
        "field": "campaignEnd",
        "message": "Missing message for error: agreement.campaign.invalidDate",
        "code": "agreement.campaign.invalidDate",
        "contextId": "eb23d5a1-b694-4b7a-a93d-858ba862749f"
    }
]

for request body containing dates formatted like:
 "campaign": {
    "start": "2019-10-01T00:00:00Z",
    "end": "2019-12-01T00:00:00Z",
    "campaignPrice": 10000
  },

**Comment by tht13** [comment]
Hi, the format is correct but the date must be in the future.

**Comment by CraigAndrew** [comment]
Thank you very much, that was it. In my case I was testing with the same campaignEndDate being 1st June 2020 and it was only yesterday that it stopped working so the boundary was subtle. May I suggest the error message be improved when "end" is in the past? I think saying "end" cannot be a past date. or "end" cannot be before "start" are 2 good error handling cases to catch than instead of having it always say "end" date is invalidDate.

**Comment by cloveras** [comment]
Good point. I have created an internal task for it. I'm closing this issue, though, and hope that's ok.
